language: php

notifications:
  email: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

before_script:
  - composer install --dev
  - composer phplint

script:
  - php vendor/bin/phpunit --coverage-clover ./test/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
