<?php
/**
 * @var \Exception|null $error
 * @var array           $last_errors
 */
?>

<?php if ($error !== null): ?>
    <b><?php echo $error->getMessage(); ?></b>

    <pre><?php echo $error->getTraceAsString(); ?></pre>
<?php endif; ?>

<?php if (count($last_errors) > 0): ?>
    <ul>
        <?php foreach ($last_errors as $last_error): ?>
            <li><?php echo $last_error; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
